# Generated by Django 5.2.13 on 2026-05-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('salon_belleza', 'Salón de Belleza'), ('peluqueria', 'Peluquería'), ('barberia', 'Barbería'), ('spa', 'Spa / Centro de Estética')], default='salon_belleza', max_length=50, verbose_name='Tipo de Negocio'),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de Instagram'),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Comercial'),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Negocio'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre del Negocio'),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
    ]
