# Generated by Django 5.2.13 on 2026-06-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Máscara de Tarjeta'),
        ),
        migrations.AddField(
            model_name='business',
            name='is_in_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='business',
            name='tbk_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Token Cliente Transbank'),
        ),
        migrations.AddField(
            model_name='business',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
