# Generated by Django 5.2.13 on 2026-06-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_appointment_client_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusiness',
            name='provides_services',
            field=models.BooleanField(default=True, verbose_name='¿Atiende clientes?'),
        ),
    ]
