# Generated by Django 5.2.13 on 2026-06-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_userbusiness_provides_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusiness',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Porcentaje de Comisión (%)'),
        ),
    ]
