# Generated by Django 5.2.13 on 2026-06-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('owner', 'Dueño de Negocio'), ('worker', 'Trabajador'), ('client', 'Cliente')], default='client', max_length=50),
        ),
    ]
