# Generated by Django 5.2.13 on 2026-06-02 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Local')),
                ('current_plan', models.CharField(choices=[('emprendedor', 'Plan Emprendedor (Staff 2)'), ('pro', 'Plan Profesional (Staff 4)'), ('luxury', 'Plan Luxury (Staff 6)')], default='pro', max_length=20)),
                ('is_in_trial', models.BooleanField(default=True)),
                ('trial_start', models.DateTimeField(auto_now_add=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('tbk_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token Cliente Transbank')),
                ('card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Máscara de Tarjeta')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
